# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ntest11',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/ntest11',
                'lib_path': 'ntest11'},
  'syms': {'ntest11.core': {'ntest11.core.foo': ('core.html#foo', 'ntest11/core.py')}}}